application: mobiletingdigital
version: 1
runtime: php55
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.(gif|png|jpg|css|mp3|js|html|json|eot|woff|woff2|ttf|svg|otf|xml|txt|pdf|zip|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|mp3|js|html|json|eot|woff|woff2|ttf|svg|otf|xml|txt|pdf|zip|ico)$
  application_readable: true

- url: /.*
  script: index.php
